$react_native_root = '../reactNativeApp/node_modules'
require_relative "#$react_native_root/react-native/scripts/react_native_pods"

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'SampleBridge', :path => '../sample-bridge'
  # pod 'KlueRN', :path => '../klue-runtime-reactnative'
  # pod 'KlueWV', :path => '../klue-runtime-webview'
  # pod 'KlueCommon', :path => '../klue-runtime-common'

  #region react native

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => "#$react_native_root/react-native",
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(
      installer,
      "#$react_native_root/react-native"
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end